#!/usr/bin/python
# vim: tabstop=4 expandtab shiftwidth=4 fileencoding=utf8
# ### BOILERPLATE ###
# Tuke - Electrical Design Automation toolset
# Copyright (C) 2008 Peter Todd <pete@petertodd.org>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ### BOILERPLATE ###


"""
Tuke software project in Python.
"""

if __name__ == "__main__":
    import locale
    locale.setlocale(locale.LC_ALL, '')

    import sys

    if (len(sys.argv) > 1) and sys.argv[1] == 'test':
        from Tuke.tests import main
        sys.argv[0] += " test"
        del sys.argv[1]
        main(sys.argv)
    else:
        from Tuke.main import main
        main(sys.argv)
