#!/usr/bin/python
# vim: tabstop=4 expandtab shiftwidth=4 fileencoding=utf8
# ### BOILERPLATE ###
# Tuke - Electrical Design Automation toolset
# Copyright (C) 2008 Peter Todd <pete@petertodd.org>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ### BOILERPLATE ###


"""
Generates a Netlist graph using pydot

Usage:

graph_netlist foo.png < foo.xml
"""

from Tuke import Id,rndId,load_element_from_file
from Tuke.sch import Component,Pin
import sys
import pydot


sch = load_element_from_file(sys.stdin)


def graph_sch(self,base = Id()):
    """Recursive grapher
    
    self - element
    base - Id prefix
    """

    pins = []
    subs = []
    for e in self.subs:
        if isinstance(e,Pin):
            pins.append(e)
        elif isinstance(e,Component):
            subs.append(e)

    # Create a pydot Node representing this component and it's pins
    n = pydot.Node(base)

    # Add each pin as a port
    l = '|'.join(
            ['<%s> %s' % (p.id,p.id) for p in pins])

    print base
    n.label = '{%s|{%s}}' % (base,l) 
    n.shape = 'Mrecord'

    nodes = [n]

    # Turn netlist entries into edges for pydot
    edges = []
    for edge in self.netlist.itervalues():
        edge = tuple(edge)
        a = edge[0]
        b = edge[1]

        
        # Pins are being implemented as graphviz ports, so we need to seperate
        # the last part of each Id
        def id_to_node_port(i):
            id_elements = str(i).split('/')
            port = id_elements.pop()
            node = '/'.join(id_elements)

            return '%s:%s' % (node,port)

        a = id_to_node_port(base + a) 
        b = id_to_node_port(base + b) 
        e = pydot.Edge(a,b)

        edges.append(e)

    for s in subs:
        n,e = graph_sch(s,base + s.id)
        nodes += n
        edges += e

    return (nodes,edges)



import pydot

(nodes,edges) = graph_sch(sch,base = sch.id)

g = pydot.Dot()

for n,e in zip(nodes,edges):
    g.add_node(n)
    g.add_edge(e)

print g.to_string()
g.write_png(sys.argv[1])
