#!/usr/bin/python
# vim: tabstop=4 expandtab shiftwidth=4 fileencoding=utf8
# ### BOILERPLATE ###
# Tuke - Electrical Design Automation toolset
# Copyright (C) 2008 Peter Todd <pete@petertodd.org>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ### BOILERPLATE ###


"""
Example Tuke-using program to generate an led grid.

Usage:

led_grid rows cols

Generates a series-parallel grid of leds and prints the resulting XML to
stdout.
"""

from Tuke import Id,rndId,save_element_to_file
from Tuke.sch import Component

class Led(Component):
    def __init__(self,id):
        Component.__init__(self,id = id)

        self.define_pins('anode','cathode')

class LedGrid(Component):
    def __init__(self,rows,cols,id):
        Component.__init__(self,id = id)

        # Define anode and cathode pins
        self.define_pins('anode','cathode')

        top_leds = []
        bottom_leds = []

        for x in range(cols):
            prev = None
            for y in range(rows):
                l = Led(id=Id('LED%s-%s' % (str(x),str(y))))
                self.add(l)

                if not prev:
                    top_leds.append(l)
                else:
                    self.netlist[prev.id + prev.p['cathode']].add(l.id + l.p['anode']) 

                prev = l

            bottom_leds.append(prev)

        # Link common anodes and cathodes
        for t in top_leds:
            self.netlist[self.p['anode']].add(t.id + t.p['anode'])
        for b in bottom_leds:
            self.netlist[self.p['cathode']].add(b.id + b.p['cathode'])

if __name__ == "__main__":
    import sys

    rows = int(sys.argv[1])
    cols = int(sys.argv[2])

    grid = LedGrid(rows,cols,id=rndId())

    save_element_to_file(grid,sys.stdout)
